### PR TITLE
Add files to gemspec, bump version

### PR DESCRIPTION
**Pull request by pletcher**
Sorry about missing this, wasn't expecting it to get merged so quickly :)

### CODE REVIEW

**Comment by pletcher** [comment]
Ping @SophieDeBenedetto

**Comment by pletcher** [comment]
Ping @SophieDeBenedetto :)

**Comment by SophieDeBenedetto** [comment]
hey @pletcher, thanks for opening this PR! I just ported this over to a [Flatiron repo](https://github.com/learn-co/learn-write). I'll merge this for now and update it on here, then future PRs can be made here https://github.com/learn-co/learn-write

UPDATE: Merged and released v 0.0.6

**Comment by pletcher** [comment]
Awesome, thanks!

**Pull request merged**
